### ISSUE TITLE
[RESOLVED] iOS app with Automatic Reconnects and long range/spotty connections can cause bluz to hang

### ISSUE THREAD

**Issue by eely22** [bluzDK/bluzDK-firmware#11]
Reported first here: http://neighborhood.bluz.io/t/bluzdk-solid-green/287/4

Reproduced at least once where the iPhone is moved away and closer several times, leading to possible reconnects and bad connections. Doesn't seem to happen with the gateway shield, but still investigating that portion.

**Comment by kennethlimcp** [comment]
:+1: as well. Saw this issue after placing device in Safe mode.

**Comment by eely22** [comment]
I believe the underlying cause had to do with an error where the socket buffer could overflow. This was also reproducible when publishing in a loop with a delay, but I think the likely reconnect/connect cycles would have the same behavior.

Further, we are using the WDT now, so any hangs like this would just reset the system. Leaving this open for the moment as I am still trying to reproduce, but this should no longer be an issue.

**Comment by eely22** [comment]
Seems to be resolved with 1.1.47
