### ISSUE TITLE
App Timer timers need to be stopped before OTA commences

### ISSUE THREAD

**Issue by gruvin** [bluzDK/bluzDK-firmware#21]
In case I/we forget ...

Since the new Timer class arrived in merge #20 -- thanks by the way -- there's a wee problem in need of attention concerning OTA Flashing.

There are 11 Nordic Soft Device App' Timers available. Timer 0 is used for the system. Timer 1 through 10 are available for user land code. If one of these triggers a callback that does anything on the Particle Cloud -- like Publish() -- it will kill the OTA process.

The solution ought to be as simple as making a HAL call to `HAL_stop_all_timers()`. However I'm not sure if we need to leave Timer 0 running during OTA or not. It's the system tick / `millis()` timer.

@eric --- Can we disable Timer 0 as well, to let it come back after reboot? Or is it needed for the OTA process?

If we need to leave Timer 0 alone, then I guess it'll just have to be a `for (int x=1; x<11;x++) HAL_app_timer_stop(x)` typeof affair.

---

Completeness:
- [ ] Minimum test case added (N/A)
- [X] Device, system and user firmware versions stated
- [ ] Genius @eely22  confirmed

**Comment by eely22** [comment]
We cannot disable the system timer. That is used to notify the WDT, so if we turn it off, the WDT times out and the system will reboot. So this will have the be selective.

It should be very simple, the cloud notifies us when the update starts so we can just add the code in here: https://github.com/bluzDK/bluzDK-firmware/blob/develop/platform/MCU/NRF51/SPARK_Firmware_Driver/src/hw_config.c#L145

**Comment by gruvin** [comment]
@eric ... Sorry, I wasn't quite accurate enough. The OTA appears to work. You get, "success". But in fact, it has not. The same app that was there before the OTA still runs after the reset -- because the OTA process didn't actually complete. Because I'm doing the OTA from the Particle Web IDE, I guess the firmware is trying to be updated as well. That takes much longer, so maybe that's why it bombs for me. {shrug}

My test app is [`applications/rtc_timer`](https://github.com/gruvin/bluzDK-firmware/blob/develop/user/applications/rtc_timer/rtc_timer.cpp). I have the D7 LED come on before publish() and off after. If that happens at the same time as the magenta light is on during OTA, things go bad.

ANYWAY ... after much to do about nothing ...

As of https://github.com/gruvin/bluzDK-firmware/commit/c72aff3e11b99e8d6e197c9559ae7b12255dda38, all ten user app_timers now get stopped before the OTA flash starts. Pull Request on its way.

OTA flash still doesn't actually work for me. But it doesn't abort now. This is a separate issues, I'm sure -- most likely simply because my firmware doesn't match the 1.1.47 version over at Particle. Haven't yet figured out how to OTA my local build -- app only, I mean.

**Comment by gruvin** [comment]
Nope. Now the bootloader compiles, the bluz module compiles ... but the app crashes on the first call to anything Timer class related, of course! It's the simple fact that a call is being made from `user-part` into `system-part1` and therefore `HAL_app_timer_*` _needs_ to be a dynalib export.

So, it's a catch 22 ...
2] Bootloader doesn't do any dynalib stuff and so it can't get an `apptimer_hal.o` to link.
2] Because Timer is used in `user-part`, it can only be a dynalib export.

OMG ... after hours of going around in circles, it just occurred to me that I should call `app_timer_stop()` DIRECTLY from `hw_config.c` -- with no HAL involved, because it's all in the same scope, right? Geeze. Trying that now ...

**Comment by eely22** [comment]
Fixed in this PR: https://github.com/bluzDK/bluzDK-firmware/commit/6bc1662f788cde60e619fe72294679f2b6a96bc7

Thanks @gruvin!
