### ISSUE TITLE
Wire.isEnabled() always returns true

### ISSUE THREAD

**Issue by telliottosceola** [bluzDK/bluzDK-firmware#26]
Noticed this during library development for I2C device.  Cannot check status of Wire like this:
if(!Wire.isEnabled()){
    Wire.begin();
}
My library never starts Wire because Wire.isEnabled always returns true even when Wire is not ready.

**Comment by eely22** [comment]
Hmm, looking at the code this should work. You can see here the function is checking the register:
https://github.com/bluzDK/bluzDK-firmware/blob/develop/hal/src/bluz/i2c_hal.c#L136

Are you attempting to use SPI at the same time? They share a register so this could cause issues. 

I will verify later this evening

**Comment by telliottosceola** [comment]
Not using SPI.  However same test code does run on a Photon no issue.  I am getting a status return of 3 when calling Wire.endTransmission which seems to be due to the port not being ready for read/write operations.  I only start Wire if isEnabled returns false.

**Comment by eely22** [comment]
There was indeed an issue with this, however the symptoms you describe seem a little off. Basically, we used a flag to determine if Wire was initialized, if it wasn't then we wouldn't initialize it in the first place. So I could enable Wire, then disable it, and never re-enable it again. This is now fixed.

I tested with the following code:

```
void setup()
{
    Serial1.begin(38400);
    Serial1.println("Welcome!");
}
void loop()
{
    if (Wire.isEnabled()) {
        Serial1.println("Wire is on!");
    } else {
        Serial1.println("Wire is off!");
    }
    Wire.begin();
    delay(4000);
    if (Wire.isEnabled()) {
        Serial1.println("Wire is on!");
    } else {
        Serial1.println("Wire is off!");
    }
    Wire.end();
}
```

With this, I received the expected output on Serial1 of:
Wire is on!
Wire is off!

Every 4 seconds. Could you re-test with the latest develop branch and verify this fixes the issue? If you are still seeing it, can you post more detailed code to reproduce the issue? I will leave open for now

**Comment by telliottosceola** [comment]
I did a pull on the latest for the devlop branch.  I saw your fix in the pull request for Wire.  However this is what I get in my serial output:

```
Wire is on!
Wire is off!
Wire is off!
Wire is off!
Wire is off!
Wire is off!
Wire is off!
Wire is off!
Wire is off!
Wire is off!
Wire is off!
Wire is off!
```

```
This is the code in my application.cpp file:
#include "application.h"
void setup(){
    Serial1.begin(115200);
}

void loop(){
    if (Wire.isEnabled()) {
        Serial1.println("Wire is on!");
    } else {
        Serial1.println("Wire is off!");
    }
    Wire.begin();
    delay(4000);
    if (Wire.isEnabled()) {
        Serial1.println("Wire is on!");
    } else {
        Serial1.println("Wire is off!");
    }
    Wire.end();
}
```

**Comment by eely22** [comment]
Did you happen to update the system part on your bluz board after you did the pull and rebuild?

**Comment by telliottosceola** [comment]
You are absolutely right Eric.  Flashed system part, working as expected now.  
Thanks
