### ISSUE TITLE
SPI.begin() seems to hijack the I2C pins as well

### ISSUE THREAD

**Issue by eely22** [bluzDK/bluzDK-firmware#34]
Initially reported here: https://neighborhood.bluz.io/t/possible-ram-space-overflow/611/10

If using a library that uses SPI, or just using SPI at all, seems to make pins D0 and D1 useless. This can be recreated with the code in the link above along with the library here: https://github.com/dhhagan/opcn2

Setting MODE to D0 or D1 always results in the digitalRead returning LOW. However, if you switch MODE to pins D2 or D3, things work as expected.

**Comment by bprobbins** [comment]
A probably related issue - D1 worked fine with attachInterrupt with v1.1.47, now is subject to spurious firing or unresponsive with v2.0.50-beta.2

**Comment by eely22** [comment]
@bprobbins I wouldn't think those are related issues. This particular problem stems from shared resources between TWI and SPI in the nrf51, while interrupts are an entirely different peripheral.

Are you using SPI or TWI and trying to use an interrupt? Or just interrupts by themselves?

I haven't seen this issue, I have tested interrupts for v2.0.50 and don't see any problems. Could you open a new issue with specific code or an example and a detailed description of the problem? What do you expect to see and what does it actually do?

Thanks!

**Comment by bprobbins** [comment]
This is the code:

```
#include "application.h"

volatile int intrflagON = 0;
volatile int intrflagOFF = 0;
volatile int intrflagBRIGHT = 0;
volatile int intrflagDIM = 0;
volatile int selectedBrightness = 1;
unsigned long lastTime = 0;
unsigned long lastTime2 = 0;

char buf[6];

void callbackON(){
    intrflagON = 1;
}

void callbackOFF(){
    intrflagOFF = 1;
}

void callbackBRIGHT(){
    intrflagBRIGHT = 1;
}

void callbackDIM(){
    intrflagDIM = 1;
}


void setup() {
  pinMode(D1, INPUT_PULLUP);
    pinMode(D2, INPUT_PULLUP);
    pinMode(D3, INPUT_PULLUP);
    pinMode(D4, INPUT_PULLUP);

//  attachInterrupt(D1, callbackDIM, FALLING);//problem here?
    attachInterrupt(D2, callbackON, FALLING);
    attachInterrupt(D3, callbackOFF, FALLING);
    attachInterrupt(D4, callbackBRIGHT, FALLING);
}//setup

void loop(){
System.sleep(SLEEP_MODE_CPU);
if (Particle.connected()) {
    unsigned long now = millis();
    if ((now - lastTime) >= 1010) { //simple debouncer??
        lastTime = now;

        if (intrflagON == 1)  {
            intrflagON  = 0;
            if (Particle.connected()) {Particle.publish("bedroomONOFF","1",60, PRIVATE);}
        }//if (intrflagON == 1)

        if (intrflagOFF == 1) {
            intrflagOFF = 0;
            if (Particle.connected()) {Particle.publish("bedroomONOFF","0",60, PRIVATE);}
        }//if (intrflagOFF == 1)


        if (intrflagBRIGHT == 1)  {
            intrflagBRIGHT  = 0;
            if (selectedBrightness < 91) {selectedBrightness = selectedBrightness  + 10;} else {selectedBrightness = 100;}
            itoa(selectedBrightness, buf, 10);
            if (Particle.connected()) {Particle.publish("bedroomBRITE", buf,60, PRIVATE);}
        }//if (intrflagON == 1)

        if (intrflagDIM == 1) {
            intrflagDIM = 0;
            if (selectedBrightness > 10) {selectedBrightness = selectedBrightness  - 10;} else {selectedBrightness = 1;}
            itoa(selectedBrightness, buf, 10);
            if (Particle.connected()) {Particle.publish("bedroomBRITE", buf,60, PRIVATE);}
        }//if (intrflagOFF == 1)

    }//if ((now - lastTime) >= 200)
}//if (Particle.connected())

}//loop
```

Basically it publishes messages that control lighting. Worked fine with 1.1.47 with all 4 interrupts as long as I edited the #define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 1 to 6
In v2.0.50-beta.2 it won't publish or does so erratically erratically when attachInterrupt(D1, callbackDIM, FALLING) is uncommented (D1 "fires" on bootup, other interrupts unresponsive). BTW I tested D1 alone as an interrupt pin and it failed there too.

**Comment by eely22** [comment]
@bprobbins I moved this over here: https://github.com/bluzDK/bluzDK-firmware/issues/35

**Comment by eely22** [comment]
@bprobbins: Could you try the following? Just put Wire.end() in your setup function as the first call, so like this:

```
void setup() {
    Wire.end();
    // rest of your code here...
}
```

It seems the driver is being activated during boot and this call works around the issue in v2.0.50-beta.2.

Let me know if that solves it for you. I will get a permanent fix in the next release. Thanks

**Comment by bprobbins** [comment]
@eely22 
Yes indeed it **does**  fix the problem with D1 (used webide with fw v2.0.50-beta.2, same code as above).
Thanks for the quick workaround!

**Comment by eely22** [comment]
This had to do with the shared resource between I2C and SPI. The registers for the two are the same, so the ENABLE register would be true if either was ON or false if either was OFF. 

The Wiring isEnabled() function only checked the register. So if either peripheral had been enabled, both Wire.isEnabled() and SPI.isEnabled() would return true.

This caused issues when trying to set the pins. The wiring library would use the pinAvailable() function, which would check if the peripheral was enabled and if it was, it wouldn't allow you to set the pins for it. So when SPI was enabled, Wire.isEnabled() returned true and the pinAvailable() function would return 0, meaning the pin was already in use.

The fix is to change the isEnabled() HAL functions to also make sure that the proper peripheral is configured. So it will return true only for the correct one when called.
