### ISSUE TITLE
HAL_SPI_Begin not setting pinMode for default or specified SS pin

### ISSUE THREAD

**Issue by pkourany** [bluzDK/bluzDK-firmware#7]
The HAL_SPI_Begin() function is not setting the pinMode() for the specified SS pin.  This may be due to the SS pin not being changed in the `spi_config` structure prior to initializing the SPI channel.

**Comment by eely22** [comment]
Added this, as well as a check to make sure it wasn't set to SPI_DEFAULT_SS which is -1 and causes issues
